[package]
name = "simpleKeychain2"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5"
chacha20poly1305 = "0.10"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
rpassword = "5"
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
